<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'active',
'actividad_economica',
'bank_cta_number',
'bank_cta_type',
'bank_name',
'contractor_address',
'contractor_arl',
'contractor_cajacompensacion',
'contractor_city',
'contractor_decljur',
'contractor_dependencia',
'contractor_dependientes',
'contractor_doc_dv',
'contractor_doc_id',
'contractor_email',
'contractor_email_mincit',
'contractor_eps',
'contractor_fondopensiones',
'contractor_id',
'contractor_image',
'contractor_lname',
'contractor_medicinapre_file',
'contractor_mobile',
'contractor_name',
'contractor_naturaleza',
'contractor_nombresfull',
'contractor_phone',
'contractor_picmonetaria_file',
'contractor_pwd',
'contractor_sup_jerarquico',
'contractor_type',
'ct_fecha_nacimiento',
'ct_fecha_nacimiento_mun',
'ct_nacionalidad',
'dem_discapacidad',
'dem_edad',
'dem_educacion',
'dem_genero',
'dem_ocupacion',
'dem_profesion',
'emergencia',
'enlace_sigep',
'factura',
'groupid',
'iva_regimen',
'pin',
'reset_date',
'reset_date1',
'reset_token',
'reset_token1',
'responsabilidades',
'signature',
'sys_date',
'sys_last_upd',
'sys_level',
'sys_status',
'sys_update',
'sys_user',
'terms_acepta',
'terms_msj',
'ubica_dep',
'ubica_extension',
'fp_code',
'fp_fecha',
'fp_file',
'contractor_tiposangre' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'active' => array( 'import_field' ),
'actividad_economica' => array( 'import_field1' ),
'bank_cta_number' => array( 'import_field2' ),
'bank_cta_type' => array( 'import_field3' ),
'bank_name' => array( 'import_field4' ),
'contractor_address' => array( 'import_field5' ),
'contractor_arl' => array( 'import_field6' ),
'contractor_cajacompensacion' => array( 'import_field7' ),
'contractor_city' => array( 'import_field8' ),
'contractor_decljur' => array( 'import_field9' ),
'contractor_dependencia' => array( 'import_field10' ),
'contractor_dependientes' => array( 'import_field11' ),
'contractor_doc_dv' => array( 'import_field12' ),
'contractor_doc_id' => array( 'import_field13' ),
'contractor_email' => array( 'import_field14' ),
'contractor_email_mincit' => array( 'import_field15' ),
'contractor_eps' => array( 'import_field16' ),
'contractor_fondopensiones' => array( 'import_field17' ),
'contractor_id' => array( 'import_field18' ),
'contractor_image' => array( 'import_field19' ),
'contractor_lname' => array( 'import_field20' ),
'contractor_medicinapre_file' => array( 'import_field21' ),
'contractor_mobile' => array( 'import_field22' ),
'contractor_name' => array( 'import_field23' ),
'contractor_naturaleza' => array( 'import_field24' ),
'contractor_nombresfull' => array( 'import_field25' ),
'contractor_phone' => array( 'import_field26' ),
'contractor_picmonetaria_file' => array( 'import_field27' ),
'contractor_pwd' => array( 'import_field28' ),
'contractor_sup_jerarquico' => array( 'import_field29' ),
'contractor_type' => array( 'import_field30' ),
'ct_fecha_nacimiento' => array( 'import_field31' ),
'ct_fecha_nacimiento_mun' => array( 'import_field32' ),
'ct_nacionalidad' => array( 'import_field33' ),
'dem_discapacidad' => array( 'import_field34' ),
'dem_edad' => array( 'import_field35' ),
'dem_educacion' => array( 'import_field36' ),
'dem_genero' => array( 'import_field37' ),
'dem_ocupacion' => array( 'import_field38' ),
'dem_profesion' => array( 'import_field39' ),
'emergencia' => array( 'import_field40' ),
'enlace_sigep' => array( 'import_field41' ),
'factura' => array( 'import_field42' ),
'groupid' => array( 'import_field43' ),
'iva_regimen' => array( 'import_field44' ),
'pin' => array( 'import_field45' ),
'reset_date' => array( 'import_field46' ),
'reset_date1' => array( 'import_field47' ),
'reset_token' => array( 'import_field48' ),
'reset_token1' => array( 'import_field49' ),
'responsabilidades' => array( 'import_field50' ),
'signature' => array( 'import_field51' ),
'sys_date' => array( 'import_field52' ),
'sys_last_upd' => array( 'import_field53' ),
'sys_level' => array( 'import_field54' ),
'sys_status' => array( 'import_field55' ),
'sys_update' => array( 'import_field56' ),
'sys_user' => array( 'import_field57' ),
'terms_acepta' => array( 'import_field58' ),
'terms_msj' => array( 'import_field59' ),
'ubica_dep' => array( 'import_field60' ),
'ubica_extension' => array( 'import_field61' ),
'fp_code' => array( 'import_field62' ),
'fp_fecha' => array( 'import_field63' ),
'fp_file' => array( 'import_field64' ),
'contractor_tiposangre' => array( 'import_field65' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid',
'import_field55' => 'grid',
'import_field56' => 'grid',
'import_field57' => 'grid',
'import_field58' => 'grid',
'import_field59' => 'grid',
'import_field60' => 'grid',
'import_field61' => 'grid',
'import_field62' => 'grid',
'import_field63' => 'grid',
'import_field64' => 'grid',
'import_field65' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'active',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'actividad_economica',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'bank_cta_number',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'bank_cta_type',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'bank_name',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'contractor_address',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'contractor_arl',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'contractor_cajacompensacion',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'contractor_city',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'contractor_decljur',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'contractor_dependencia',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'contractor_dependientes',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'contractor_doc_dv',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'contractor_doc_id',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'contractor_email',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'contractor_email_mincit',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'contractor_eps',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'contractor_fondopensiones',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'contractor_id',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'contractor_image',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'contractor_lname',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'contractor_medicinapre_file',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'contractor_mobile',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'contractor_name',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'contractor_naturaleza',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'contractor_nombresfull',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'contractor_phone',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'contractor_picmonetaria_file',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'contractor_pwd',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'contractor_sup_jerarquico',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'contractor_type',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'ct_fecha_nacimiento',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'ct_fecha_nacimiento_mun',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'ct_nacionalidad',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'dem_discapacidad',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'dem_edad',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'dem_educacion',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'dem_genero',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'dem_ocupacion',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'dem_profesion',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'emergencia',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'enlace_sigep',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'factura',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'groupid',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'iva_regimen',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'pin',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'reset_date',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'reset_date1',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'reset_token',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'reset_token1',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'responsabilidades',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'signature',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'sys_date',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'sys_last_upd',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'sys_level',
'type' => 'import_field' ),
'import_field55' => array( 'field' => 'sys_status',
'type' => 'import_field' ),
'import_field56' => array( 'field' => 'sys_update',
'type' => 'import_field' ),
'import_field57' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field58' => array( 'field' => 'terms_acepta',
'type' => 'import_field' ),
'import_field59' => array( 'field' => 'terms_msj',
'type' => 'import_field' ),
'import_field60' => array( 'field' => 'ubica_dep',
'type' => 'import_field' ),
'import_field61' => array( 'field' => 'ubica_extension',
'type' => 'import_field' ),
'import_field62' => array( 'field' => 'fp_code',
'type' => 'import_field' ),
'import_field63' => array( 'field' => 'fp_fecha',
'type' => 'import_field' ),
'import_field64' => array( 'field' => 'fp_file',
'type' => 'import_field' ),
'import_field65' => array( 'field' => 'contractor_tiposangre',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>