<?php
			$optionsArray = array( 'totals' => array( 'cert_id' => array( 'totalsType' => '' ),
'cert_hash' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'cont_hash_fk' => array( 'totalsType' => '' ),
'cert_califcumpli' => array( 'totalsType' => '' ),
'cert_obliga' => array( 'totalsType' => '' ),
'cert_obs' => array( 'totalsType' => '' ),
'cert_fecha' => array( 'totalsType' => '' ),
'cert_status' => array( 'totalsType' => '' ),
'cert_mailsol' => array( 'totalsType' => '' ),
'cert_fechacarga' => array( 'totalsType' => '' ),
'cert_file' => array( 'totalsType' => '' ),
'cert_estado' => array( 'totalsType' => '' ),
'cert_mailnot' => array( 'totalsType' => '' ),
'sol_user' => array( 'totalsType' => '' ),
'cer_numcontrato' => array( 'totalsType' => '' ),
'cer_vigencia' => array( 'totalsType' => '' ),
'cer_nombres' => array( 'totalsType' => '' ),
'cer_doc_tipo' => array( 'totalsType' => '' ),
'cer_doc_num' => array( 'totalsType' => '' ),
'cer_objeto' => array( 'totalsType' => '' ),
'cer_valor_num' => array( 'totalsType' => '' ),
'cer_valor_letra' => array( 'totalsType' => '' ),
'cer_plazo' => array( 'totalsType' => '' ),
'cer_fecha_suscripcion' => array( 'totalsType' => '' ),
'cer_fecha_inicio' => array( 'totalsType' => '' ),
'cer_fecha_fin' => array( 'totalsType' => '' ),
'cer_estado_contrato' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cert_califcumpli',
'cert_estado',
'cert_fecha',
'cert_hash',
'cert_id',
'cert_mailnot',
'cert_obs',
'id_cont_fk',
'sol_user',
'cert_status',
'cont_hash_fk',
'cer_doc_num',
'cer_doc_tipo',
'cer_estado_contrato',
'cer_fecha_fin',
'cer_fecha_inicio',
'cer_fecha_suscripcion',
'cer_nombres',
'cer_numcontrato',
'cer_objeto',
'cer_plazo',
'cer_valor_letra',
'cer_valor_num',
'cer_vigencia' ),
'exportFields' => array( 'cert_califcumpli',
'cert_estado',
'cert_fecha',
'cert_hash',
'cert_id',
'cert_mailnot',
'cert_obs',
'id_cont_fk',
'sol_user',
'cert_status',
'cont_hash_fk',
'cer_doc_num',
'cer_doc_tipo',
'cer_estado_contrato',
'cer_fecha_fin',
'cer_fecha_inicio',
'cer_fecha_suscripcion',
'cer_nombres',
'cer_numcontrato',
'cer_objeto',
'cer_plazo',
'cer_valor_letra',
'cer_valor_num',
'cer_vigencia' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cert_califcumpli' => array( 'export_field' ),
'cert_estado' => array( 'export_field1' ),
'cert_fecha' => array( 'export_field2' ),
'cert_hash' => array( 'export_field5' ),
'cert_id' => array( 'export_field6' ),
'cert_mailnot' => array( 'export_field7' ),
'cert_obs' => array( 'export_field10' ),
'id_cont_fk' => array( 'export_field13' ),
'sol_user' => array( 'export_field3' ),
'cert_status' => array( 'export_field4' ),
'cont_hash_fk' => array( 'export_field8' ),
'cer_doc_num' => array( 'export_field9' ),
'cer_doc_tipo' => array( 'export_field11' ),
'cer_estado_contrato' => array( 'export_field12' ),
'cer_fecha_fin' => array( 'export_field14' ),
'cer_fecha_inicio' => array( 'export_field15' ),
'cer_fecha_suscripcion' => array( 'export_field16' ),
'cer_nombres' => array( 'export_field17' ),
'cer_numcontrato' => array( 'export_field18' ),
'cer_objeto' => array( 'export_field19' ),
'cer_plazo' => array( 'export_field20' ),
'cer_valor_letra' => array( 'export_field21' ),
'cer_valor_num' => array( 'export_field22' ),
'cer_vigencia' => array( 'export_field23' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field5',
'export_field6',
'export_field7',
'export_field10',
'export_field13',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field11',
'export_field12',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field10' => 'grid',
'export_field13' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field5',
'export_field6',
'export_field7',
'export_field10',
'export_field13',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field11',
'export_field12',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field5',
'export_field6',
'export_field7',
'export_field10',
'export_field13',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field11',
'export_field12',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'cert_califcumpli',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'cert_estado',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'cert_fecha',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cert_hash',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cert_id',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'cert_mailnot',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'cert_obs',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'id_cont_fk',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'sol_user',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'cert_status',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'cont_hash_fk',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'cer_doc_num',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'cer_doc_tipo',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'cer_estado_contrato',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'cer_fecha_fin',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'cer_fecha_inicio',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'cer_fecha_suscripcion',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'cer_nombres',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'cer_numcontrato',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'cer_objeto',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'cer_plazo',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'cer_valor_letra',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'cer_valor_num',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'cer_vigencia',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>