<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'cert_califcumpli',
'cert_estado',
'cert_fecha',
'cert_hash',
'cert_id',
'cert_mailnot',
'cert_obs',
'id_cont_fk',
'sol_user',
'cert_status',
'cont_hash_fk',
'cer_doc_num',
'cer_doc_tipo',
'cer_estado_contrato',
'cer_fecha_fin',
'cer_fecha_inicio',
'cer_fecha_suscripcion',
'cer_nombres',
'cer_numcontrato',
'cer_objeto',
'cer_plazo',
'cer_valor_letra',
'cer_valor_num',
'cer_vigencia' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cert_califcumpli' => array( 'import_field' ),
'cert_estado' => array( 'import_field1' ),
'cert_fecha' => array( 'import_field2' ),
'cert_hash' => array( 'import_field5' ),
'cert_id' => array( 'import_field6' ),
'cert_mailnot' => array( 'import_field7' ),
'cert_obs' => array( 'import_field10' ),
'id_cont_fk' => array( 'import_field13' ),
'sol_user' => array( 'import_field3' ),
'cert_status' => array( 'import_field4' ),
'cont_hash_fk' => array( 'import_field8' ),
'cer_doc_num' => array( 'import_field9' ),
'cer_doc_tipo' => array( 'import_field11' ),
'cer_estado_contrato' => array( 'import_field12' ),
'cer_fecha_fin' => array( 'import_field14' ),
'cer_fecha_inicio' => array( 'import_field15' ),
'cer_fecha_suscripcion' => array( 'import_field16' ),
'cer_nombres' => array( 'import_field17' ),
'cer_numcontrato' => array( 'import_field18' ),
'cer_objeto' => array( 'import_field19' ),
'cer_plazo' => array( 'import_field20' ),
'cer_valor_letra' => array( 'import_field21' ),
'cer_valor_num' => array( 'import_field22' ),
'cer_vigencia' => array( 'import_field23' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field5',
'import_field6',
'import_field7',
'import_field10',
'import_field13',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field11',
'import_field12',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field10' => 'grid',
'import_field13' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field5',
'import_field6',
'import_field7',
'import_field10',
'import_field13',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field11',
'import_field12',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field5',
'import_field6',
'import_field7',
'import_field10',
'import_field13',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field11',
'import_field12',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'cert_califcumpli',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cert_estado',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'cert_fecha',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cert_hash',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'cert_id',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'cert_mailnot',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'cert_obs',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'id_cont_fk',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'sol_user',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'cert_status',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cont_hash_fk',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cer_doc_num',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'cer_doc_tipo',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'cer_estado_contrato',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'cer_fecha_fin',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'cer_fecha_inicio',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'cer_fecha_suscripcion',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'cer_nombres',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'cer_numcontrato',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'cer_objeto',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'cer_plazo',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'cer_valor_letra',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'cer_valor_num',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'cer_vigencia',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>