<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => '',
'emailField' => 'contractor_email',
'extUserIdField' => '',
'fullnameField' => 'contractor_nombresfull',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'contractor_pwd',
'phoneField' => 'phone1',
'resetDateField' => 'reset_date1',
'resetTokenField' => 'reset_token1',
'table' => array( 'connId' => 'dbct_at_localhost',
'table' => 'contractor_master' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'contractor_doc_id',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'FNnt4D7qPY1XyKf6dyOK',
'JWTSecret' => 'G0LCddvpGgIbjmvB0Xng' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 1,
'adminEmail' => '',
'caseInsensitiveLogin' => false,
'changePasswordPage' => true,
'changePwdPage' => true,
'hashPassword' => true,
'notifyAdmin' => false,
'notifyUser' => false,
'registerPage' => false,
'remindPage' => true,
'remindPasswordPage' => true,
'sendActivationLink' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'notificaciones@jcc.gov.co',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp.office365.com',
'SMTPPort' => 587,
'SMTPUser' => 'notificaciones@jcc.gov.co',
'SMTPPassword' => 'w%^u9Qcd!!36',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false,
'tables' => array( 'Dashboard' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_members' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_rights' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cert_master_1' => array( 'mainOwnerIDField' => 'sol_user',
'securityOption' => 1,
'userOwnerIDField' => 'contractor_doc_id' ),
'contractor_master' => array( 'mainOwnerIDField' => 'contractor_doc_id',
'securityOption' => 1,
'userOwnerIDField' => 'contractor_doc_id' ),
'contractor_master_Chart_genero' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contractor_master_chart_eps' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contractor_master_chart_fondopension' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contractor_master_jur' => array( 'mainOwnerIDField' => 'contractor_doc_id',
'securityOption' => 1,
'userOwnerIDField' => 'contractor_doc_id' ),
'contractor_master_signature' => array( 'mainOwnerIDField' => 'contractor_doc_id',
'securityOption' => 1,
'userOwnerIDField' => 'contractor_doc_id' ),
'contractor_master_view' => array( 'mainOwnerIDField' => 'contractor_doc_id',
'securityOption' => 0,
'userOwnerIDField' => 'contractor_doc_id' ),
'contrato' => array( 'mainOwnerIDField' => 'cont_nit_contra_ta',
'securityOption' => 1,
'userOwnerIDField' => 'contractor_doc_id' ),
'contrato_attached' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_attached_type' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contrato_tipo_unidad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dependencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dependencias_001' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_documents' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'hoja_ruta_2020_tracking' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_4' => array( 'mainOwnerIDField' => 'inf_doccontratista',
'securityOption' => 1,
'userOwnerIDField' => 'contractor_doc_id' ),
'informe_intersup_anexos_contratista' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_anexos_contratista_o' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_anexos_tipo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_contratista' => array( 'mainOwnerIDField' => 'inf_doccontratista',
'securityOption' => 1,
'userOwnerIDField' => 'contractor_doc_id' ),
'informe_intersup_cxc' => array( 'mainOwnerIDField' => 'cxc_numdoc',
'securityOption' => 1,
'userOwnerIDField' => 'contractor_doc_id' ),
'informe_intersup_cxc_old' => array( 'mainOwnerIDField' => 'cxc_numdoc',
'securityOption' => 0,
'userOwnerIDField' => 'contractor_doc_id' ),
'informe_intersup_estado' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_oe' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_oe_contratista' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'informe_intersup_plan_pagos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'interventor_interno' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'interventor_periodos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nomina_cont_meses' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_001_dashboard' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_bandejaentrada_supervisores' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_consulta_op' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_divipola' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_genera_informe' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_inf_plandepagos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_cxc' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_banco' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_cta_banco' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_docidentidad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tipo_regimen' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_cajacomp' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_ciiu' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_discapacidad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_fondopension' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_fondosalud' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_genero' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_gruposanguineo' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_naturaleza' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_reponsabilidades' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_sn' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_sn_oe' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_arl' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipopago' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'dbct_at_localhost',
'table' => 'gestioncontratistas_audit' ),
'lockingTable' => array( 'connId' => 'dbct_at_localhost',
'table' => 'gestioncontratistas_locking' ),
'tables' => array( 'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'cert_master_1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'contractor_master' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contractor_master_jur' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contractor_master_signature' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contractor_master_view' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_attached' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'contrato_attached_type' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'contrato_tipo_unidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'dependencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencias_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_documents' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'global_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'hoja_ruta_2020_tracking' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'informe_intersup_4' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_anexos_contratista' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'informe_intersup_anexos_contratista_o' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'informe_intersup_anexos_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'informe_intersup_contratista' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_cxc' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'informe_intersup_cxc_old' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'informe_intersup_estado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_oe' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'informe_intersup_oe_contratista' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'informe_intersup_plan_pagos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'interventor_interno' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'interventor_periodos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nomina_cont_meses' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'q_001_dashboard' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'q_bandejaentrada_supervisores' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'q_consulta_op' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'q_divipola' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_genera_informe' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'q_inf_plandepagos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'q_info_cxc' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'tipo_banco' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_cta_banco' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_docidentidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_regimen' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_cajacomp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_ciiu' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'tparam_discapacidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_fondopension' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_fondosalud' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_genero' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_gruposanguineo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'tparam_naturaleza' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'tparam_reponsabilidades' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'tparam_sn' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_sn_oe' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_arl' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipopago' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => false,
'remember' => false,
'types' => array(  ),
'twoFactorField' => '˂Create new˃',
'emailField' => 'contractor_email',
'phoneField' => '˂Create new˃',
'codeField' => '˂Create new˃',
'projectName' => 'GestionContratistas_v109' ),
'projectName' => 'GestionContratistas_v1091',
'loginDataSource' => 'contractor_master',
'loginForm' => 1,
'dynamicPermissions' => true,
'dpTablePrefix' => 'gestioncontratistas_',
'dpTableConnId' => 'dbct_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '00',
'codeField' => '',
'emailField' => 'contractor_email',
'extUserIdField' => '',
'fullnameField' => 'contractor_nombresfull',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'contractor_pwd',
'phoneField' => 'phone1',
'resetDateField' => 'reset_date1',
'resetTokenField' => 'reset_token1',
'table' => array( 'connId' => 'dbct_at_localhost',
'table' => 'contractor_master' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'contractor_doc_id',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>